import 'package:flutter/material.dart';

abstract class AppColors {
  static const scaffoldBg = Color(0xFFF9F9F9);
  static const registerBg = Color(0xFF242424);
  static const main = Color(0xFF1E1F28);
  static const navyBlue = Color(0xFF147BEA);
  static const lightBlue = Color(0xFF3B70CA);
  static const grey605 = Color(0xFF9EA2B2);
  static const grey20 = Color(0xFFF5F5F7);
  static const grey40 = Color(0xFFCACCD4);
  static const grey60 = Color(0xFFBBBECA);
  static const grey80 = Color(0xFF9EA2B2);
  static const grey90 = Color(0xFF7E8194);
  static const purpleLight = Color(0xFFE9EEFF);
  static const yellowLight = Color(0xFFFFF5D1);
  static const greenLight = Color(0xFFF0F8F2);
  static const greenText = Color(0xFF54B876);
  static const greyText = Color(0xFFABB4BD);
  static const greyBorder = Color(0xFFBDBDBD);
  static const cardGrey = Color(0xFFE0E0E0);
  static const greyCircle = Color(0xFFD9D9D9);
  static const grey2 = Color(0xFF4F4F4F);
  static const greyDark = Color(0xFF333333);
  static const dark = Color(0xFF2A2C36);
  static const black = Color(0xFF222222);
  static const red = Color(0xFFC20C0D);
  static const redIcon = Color(0xFFEA2D2D);
  static const bgError = Color(0xFFFDF3F3);
  static const bgActive = Color(0xFFF2F5FF);
  static const blue = Color(0xFF2B77DD);
  // static const lightBlue = Color(0xFF2F80ED);
  static const blueDark = Color(0xFF2B729B);
  static const inactiveColor = Color(0xFFB0B4C0);
  static const brown = Color(0xFFDDC8C3);
  static const lightBlack = Color(0xFF404040);
  static const lightGrey = Color(0xFFC4C4C4);
  static const lightWhite = Color(0xFFF2F2F2);
  static const lightWhite20 = Color(0xFFF8F9FB);
  static const dividerGrey = Color(0xFFE0E0E0);
  static const yellow = Color(0xFFFFCF2B);
  static const grayBorder = Color(0xFFC1C6D0);
  static const bgBottomSheet = Color(0xFFF2F2F6);
  static const grey700 = Color(0xFF9499A4);
  static const specDivider = Color(0xFFEBEDF1);
  static const specLiner = Color(0xFFCACCD5);
  static const neutral500 = Color(0xFFBBC0CB);
  static const neutral800 = Color(0xFF656A76);
  static const yellowButton = Color(0xFFF5C136);
  static const greyTabBar = Color(0xFFE8E9EE);
  static const neutralGrey = Color(0xFFF3F5F8);
  static const bluePercent = Color(0xFF20adda);

  static const gradientRed = LinearGradient(colors: [red, Color(0xFFAC0A0B)]);
}
